### ISSUE TITLE
`npm run build` is not hooked

### ISSUE THREAD

**Issue by lenowng** [yohangz/scala-play-react-seed#17]
First and foremost, this project is a great seed!

1. Given: `'/' is project root`
I might be getting the context wrong here but it seems that I can't have my `/public` updated upon file changes in `/ui/src/*`. Could be probably be related to `build.sbt` on line `..watchSources ++= (baseDirectory.value / "public/ui" ** "*").get`? I don't see the relevancy of `/public/ui` here

2. Might be a good idea on generating the `public` assets onBefore cycle (`localhost:9000/` won't work when there is no `index.html`)
`FrontendRunHook.scala`:
```
      override def beforeStarted(): Unit = {
        if (!(base / "ui" / "node_modules").exists()) Process(yarnInstall, base / "ui").!
        if (!(base / "public").exists()) Process(npmBuild, base / "ui").!
      }
```

Please clarify things for me, I can help with pull requests!

**Comment by yohangz** [comment]
@lenowng sorry about the delayed response, please find my answers as follows,

1. Great catch. It is not required to watch the ```public/ui``` dir. It is safe to remove that code line.

2. When you run the project on what mode it will never consume the play backend root route as we run an isolated server which is hosting the frontend project while it accesses the backend api resources via a reverse proxy. There is no such importance as we would never access ```localhost:9000``` entry to access the app on watch mode. We have a pre-build hook in place to trigger frontend build prior to generating the build artifact which will ensure that frontend build will be available in public dir for the play app distribution build consumption.

Appreciate if you can send a PR addressing the first issue.

**Comment by lenowng** [comment]
@yohangz Thanks for the clarification on point `2.` but I can't commit a PR as I have not access to the repo at the moment.
