### ISSUE TITLE
Action Not Found For request 'GET /'

### ISSUE THREAD

**Issue by EugeunieOrz** [yohangz/scala-play-react-seed#27]
Hello, I'm trying to run scala-play-react-seed and get the following errors:

1) Before updating packages in `package.json` loading localhost:9000 in browser gave me the following output: 
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

2) After updating packages in `package.json` I've got:

    Action Not Found
    For request 'GET /'
    These routes have been tried, in this order:
    1 GET  /                        controllers.FrontendController.index()
    2 GET  / api/summary   controllers.HomeController.appSummary
    3 GET / $file<.+>          controllers.FrontendController.assetOrDefault(file:String)

**Comment by yohangz** [comment]
@EugeunieOrz, could you provide more context on this issue? environment details, which command you ran, etc.

**Comment by EugeunieOrz** [comment]
In command-line on Windows 10 in `ui` folder of the project I ran `npm install`, after that I launched `sbt` in root project folder, then `[scala-play-react-seed] $ run`. 

Afterwards, I've got the following:

`[warn] play-functional_2.12-2.8.1.jar no longer exists at C:\Users\eugen\Documents\scala-play-react-seed-master-before-update\null\Coursier\cache\v1\https\repo1.maven.org\maven2\com\typesafe\play\play-functional_2.12\2.8.1\play-functional_2.12-2.8.1.jar
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

> scala-play-react-seed@1.0.0 start C:\Users\eugen\Documents\scala-play-react-seed-master\ui
> react-scripts start

i ∩╜ówds∩╜ú: Project is running at http://192.168.0.101/
i ∩╜ówds∩╜ú: webpack output is served from
i ∩╜ówds∩╜ú: Content not from webpack is served from C:\Users\eugen\Documents\scala-play-react-seed-master\ui\public
i ∩╜ówds∩╜ú: 404s will fallback to /
Starting the development server...

[info] Compiling 7 Scala sources and 1 Java source to C:\Users\eugen\Documents\scala-play-react-seed-master\target\scala-2.12\classes ...
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter

[info] play.api.Play - Application started (Dev) (no global state)`

I launched `locakhost:9000` in the browser and got the following output:
 
`Action Not Found
For request 'GET /'
These routes have been tried, in this order:
1 GET / controllers.FrontendController.index()
2 GET / api/summary controllers.HomeController.appSummary
3 GET / $file<.+> controllers.FrontendController.assetOrDefault(file:String)`

**Comment by yohangz** [comment]
Duplicate of #26 

Ideally, it should open the browser window on watch mode. Please check the status of the original issue.

**Comment by cyrilfr** [comment]
I've the exact same issue under Windows (but not under Linux), with Play 2.8.8.
