### ISSUE TITLE
controllers.Assets.at returns 404 when looking for a React route

### ISSUE THREAD

**Issue by fralken** [yohangz/scala-play-react-seed#3]
Your solution is very clever and I managed to merge a non trivial React application into a Play application.

There was one problem, though. React routes (that are not resources) are obviously not found by `controllers.Assets.at()` which returns 404. It should return the main page `index.html` that processes the routes correctly.

This problem is explained in issue [#7634](https://github.com/playframework/playframework/issues/7634) of Playframework.

A solution I found is to implement a controller like so:
```
@Singleton
class SpaController @Inject()(assets: Assets,
                              cc: ControllerComponents)
                             (implicit ec: ExecutionContext)
  extends AbstractController(cc) {

  def index = assets.at("index.html")

  def assetOrDefault(resource: String) = if (resource.contains(".")) assets.at(resource) else index
}
```
and add these routes to the `routes` file:
```
# first route
GET        /             controllers.SpaController.index()

# last route
GET        /*file        controllers.SpaController.assetOrDefault(file)
```

**Comment by yohangz** [comment]
I didn't come across this issue because i was using [hash location strategy](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md) based routing. However, I will apply the mentioned fix. Thanks for the detailed bug report and fix suggestion.
