### ISSUE TITLE
"sbt test" hangs when "npm run test" is waiting for user input

### ISSUE THREAD

**Issue by fralken** [yohangz/scala-play-react-seed#4]
When running `sbt test`, `npm run test` is first executed in watch mode, but it cannot receive user input so it hangs.

The workaround I found is to disable watch mode by enabling CI, with CI=true. That is in `package.json` change the line `test` like so:

```
  "scripts": {
    "start": ...,
    "build": ...,
    "test": "CI=true react-scripts test --env=jsdom",
    ...
   }
```

I haven't figured out how to let `Process()` receive input from standard input.

**Comment by yohangz** [comment]
My bad, I have forgotten to apply the fix for this issue in [Scala Play ](https://github.com/yohangz/scala-play-react-seed) seed, Although had this fixed in [Java Play ](https://github.com/yohangz/java-play-react-seed) seed
