### ISSUE TITLE
Deployment to Heroku requires package.json under root directory

### ISSUE THREAD

**Issue by haozhou** [yohangz/scala-play-react-seed#8]
Hi,
I'm trying to deployment the app to Heroku.
I already added buildpack "https://github.com/mars/create-react-app-buildpack" to the application
But it doesn't work since the package.json is placed under ui/ instead of the root directory.

So the build system complains that " App not compatible with buildpack: https://github.com/mars/create-react-app-buildpack.git"
Is there any solution other than duplicating the file or create a symbol link?

Thanks

**Comment by yohangz** [comment]
Hi @haozhou,

This seed is bundling the react application source within play project distribution artifact when you run ```sbt dist``` 

You just have to setup Heroku for play application which will contain all the necessary frontend and backend components.

Please go through the [React with Play Framework 2.6.x](http://bit.ly/2A1AzEq) article which explains how this seed project works.

**Comment by haozhou** [comment]
I do setup my heroku app to use buildpack "create-react-app-buildpack"
Are you suggesting that we should compile and build the react app locally and bundle that into the scala app which will be compiled on heruko later?

Thanks.

**Comment by yohangz** [comment]
Play scala app distribution itself will bundle react app codebase to scale project distribution and when you host, it will server both forntend and backend which is the idea of this seed. You don't have to use ```create-react-app-buildpack```.

**Comment by mikepigott** [comment]
Hi, I'm actually having the same problem.  If I deploy this to Heroku as a Scala / Play! project, I get the error `remote: env: ‘npm’: No such file or directory`.

However, if I try to add a Node.JS buildpack to the project, I get the error:
```
remote:  !     ERROR: Application not supported by 'heroku/nodejs' buildpack
remote:  !     
remote:  !     The 'heroku/nodejs' buildpack is set on this application, but was
remote:  !     unable to detect a Node.js codebase.
remote:  !         
remote:  !     A Node.js app on Heroku requires a 'package.json' at the root of
remote:  !     the directory structure.
```

Is there anything I can do to fix this?

**Comment by mikepigott** [comment]
I ultimately got this to work.  Here's what I did:

1. I had Heroku run a Node buildpack first, and a Scala buildpack second.
```
$ heroku buildpacks:add heroku/nodejs
$ heroku buildpacks:add heroku/scala
Buildpack added. Next release on <project> will use:
  1. heroku/nodejs
  2. heroku/scala
```

2. I copied the `ui/package.json` to the project's root directory.
3. I changed the build command for the root `package.json` to `cd ui && rimraf ../public && react-scripts build && ncp build ../public && rimraf build`
   * The only change was to `cd` into the `ui` directory first before executing the commands.
4. Finally, I commented out the line `stage := (stage dependsOn `ui-prod-build`).value` in `ui-build.sbt`, for two reasons:
   * The Node.JS build already runs these commands.
   * The `ncp` command is no longer available when Heroku runs `sbt stage`.

These changes allowed me to get my project successfully deployed on Heroku.

**Comment by slugmandrew** [comment]
@mikepigott Could you clarify something for me please? 

* You still retain the original `ui/package.json`, along with the out-of-the-box commands like `"start": "react-scripts start"`.
* You duplicate that `package.json` in the project root, changing the commands as mentioned (adding the `cd ui &&` bit before)
* Heroku will deploy the UI from the root, using `node_modules`.
* Locally we deploy the UI from `/ui`, using `/ui/node_modules`.

I recently ran into some issues with having nested modules folders and just want to understand a bit better. Thanks for the help, your posts here helped me get deployed on Heroku so I really appreciate it.

**Comment by mikepigott** [comment]
@slugmandrew, sorry - I didn't see this until just now.

* Correct - I retain the original `ui/package.json` is retained - it's still needed to run local builds via sbt.  Any changes you make to one need to be copied to the other.
* Correct - again, any changes you make to one need to be copied to the other.
* Correct
* Correct - sbt will do this for you

I hope you were able to figure it out!

**Comment by SunPj** [comment]
No need to copy entire `package.json` file and keep it in sync.

Just creating one with following content in root path is sufficient 
```
{
  "name": "play-scala-react-seed",
  "version": "0.0.1",
  "scripts": {
    "postinstall": "cd ui && npm install && npm run build"
  },
  "devDependencies": {
    "ncp": "^2.0.0",
    "prettier": "^2.8.5",
    "rimraf": "^4.1.3"
  }
}
```
