### ISSUE TITLE
appSummary route in homeController doesn't seem to work

### ISSUE THREAD

**Issue by deprosun** [yohangz/scala-play-react-seed#9]
The console finally errors out with "error_empty_response". 

How to produce this error:
1. Clone the repo
2. Run sbt run
3. notice the welcome page saying "Welcome to!" and never updates to "Welcome to Scala Play React Seed"

**Comment by deprosun** [comment]
made a pull request to fix this issue. I guess we need to have localhost:9000 as allowed host

https://github.com/yohangz/scala-play-react-seed/pull/10

**Comment by yohangz** [comment]
ty, will apply the same update to other seed projects

**Comment by deprosun** [comment]
@yohangz  this is bizarre. So my fix was working and I hence made the PR. A day later, I run the fixed version, its back to the same result. It hung at "Welcome to!".. the conf/application.conf shows allowed hosts as ["localhost:9000"]

I have no clue why its back to the issue again. I would reopen this. Were you able to reproduce this?

**Comment by yohangz** [comment]
I validated the same from my end and it works perfectly fine. 

Open the browser developer tools and verify the http status of:
```http://localhost:3000/api/summary```

Also, try to call the summary API directly via ```http://localhost:9000/api/summary``` and verify whether it is working fine. Verify whether both 3000 and 9000 ports are not used prior to running the application.

Furthermore can you share your platform details (OS and Browser).

**Comment by deprosun** [comment]
@yohangz thanks for the confirmation. 

> Open the browser developer tools and verify the http status of:
> `http://localhost:3000/api/summary`
The console eventually shows this error message .
![image](https://user-images.githubusercontent.com/5571798/49450800-ca483c00-f7ab-11e8-984d-e961adcf865d.png)

> Also, try to call the summary API directly via `http://localhost:9000/api/summary` and verify whether it is working fine. Verify whether both 3000 and 9000 ports are not used prior to running the application.

I called `http://localhost:9000/api/summary` from the browser and curl. Works fine. Both client and the server are up in 3000 and 9000 respectively, so I don't think those ports are used anywhere else.

> Furthermore can you share your platform details (OS and Browser).
OS: macOS Sierra (version 10.12.6)
Browser: Google Chrome (version 70.0.3538.110)

Other things I tried:
* Delete the `node_modules` folder and redownload all the npm dependencies. No luck
* I also cleaned out sbt caches. No luck
* I changed `conf/application.conf` to have `hosts.allowed` from `"localhost:9000"` to `"."`. No luck

😕

**Comment by deprosun** [comment]
@yohangz okay found out that 9000 port is being listened by a lot of application. Command to find this : `lsof -i :9000`

```
$ lsof -i :9000
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    11252 kgupta  113u  IPv4 0xdcadbfd193f7d3bf      0t0  TCP localhost:65186->localhost:cslistener (ESTABLISHED)
Google    11252 kgupta  127u  IPv4 0xdcadbfd194352ea7      0t0  TCP localhost:65037->localhost:cslistener (CLOSED)
Google    11252 kgupta  142u  IPv4 0xdcadbfd193214097      0t0  TCP localhost:64814->localhost:cslistener (ESTABLISHED)
Google    11252 kgupta  220u  IPv4 0xdcadbfd19325e79f      0t0  TCP localhost:65041->localhost:cslistener (CLOSED)
Google    11252 kgupta  224u  IPv4 0xdcadbfd19a95098f      0t0  TCP localhost:64977->localhost:cslistener (CLOSED)
Google    11252 kgupta  234u  IPv4 0xdcadbfd1935a679f      0t0  TCP localhost:65039->localhost:cslistener (CLOSED)
```

We want to use a port that returns nothing when `lsof -i :<PORT>` is run.

I change the play port to an unused port `:8080` and change the proxy setting to `localhost:8080`, then it worked. 

I wanted to see if I needed to fix the issue I did of adding `localhost:9000` to `play.filters.host.allowed`, I didn't. I commented it out and ran it on 8080, it still worked. So I don't think we need the fix I made..

**Comment by yohangz** [comment]
@deprosun, i'm have the same platform and everything is working fine.

Few more things to try:
- Use another browser and verify the same.
- Send me the full console log with fetch failure error so then i can investigate further on what is going on, including any warnings on console log.
- Share the network log in dev tools. Specifically summary call details.
- Prepare a distribution build and verify whether it is working fine.
- Also, try restarting the machine which sounds dumb but just give it a try.

**Comment by yohangz** [comment]
@deprosun, just saw your response. Yes, i also tried without allowed hosts and it working fine. Seems like localhost is allowed by default. 

However, thanks for the prompt response. I will revert the changes made made.
